import type { Metadata } from "next";
import { Public_Sans, PT_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import TreasurerHydrator from "@/app/components/TreasurerHydrator";


const publicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-public-sans",
});

const ptSans = PT_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-pt-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${publicSans.variable} ${ptSans.variable}`}>
        <body>
          {children}
          <TreasurerHydrator />
        </body>
      </html>
    </ClerkProvider>
  );
}